version: '2'

services:
    db:
      image: mariadb
      environment:
                - MYSQL_DATABASE=yzdemo
                - MYSQL_USER=yzdemo
                - MYSQL_PASSWORD=yzdemo_password
                - MYSQL_ROOT_PASSWORD=root
      volumes:
            - ./db:/var/lib/mysql
            - /etc/localtime:/etc/localtime:ro
      ports:
            - "33061:3306"
    phpmyadmin:
     image: phpmyadmin/phpmyadmin
     environment:
            MYSQL_USER: yzdemo
            MYSQL_PASSWORD: yzdemo_password
            MYSQL_ROOT_PASSWORD: root
     ports:
            - "8012:80"
     links:
            # for mysql container
            - "db:db"
volumes:
    db:
        driver: "local"